import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/subjectme.jpg"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
  
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'> 
     
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/3'>
              <Image src={profilePic} alt='AbenaPoku' className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text='Turning Visions into Visuals with Code' className='!text-6xl !text-left'/>
              <p className='my-4 text-base font-medium'> As a passionate web developer, I aim to breathe life into digital dreams,
                 crafting immersive experiences that captivate and inspire.</p>
                 <div className='flex items-center self-start mt-2'>
                  <Link href='/dummy.pdf' target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark'
                  download={true}>Resume <LinkArrow className={'w-6 ml-1'}/>
                  </Link>
                  <Link href='mailto:abenapoku2112@gmail.com' target={"_blank"}
                  className='ml-4 text-lg font-medium capitalize text-dark underline'>
                    Contact</Link>
                 </div>
            </div>
          </div>
        </Layout>

        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt='AbenaPoku' className='w-full h-auto'/>
        </div>
        </main>

    </>
  )
}
